apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
spec:
  ports:
    - name: "7687"
      port: 7687
      targetPort: 7687
    - name: "7474"
      port: 7474
      targetPort: 7474
  selector:
    app: database
